---
- name: install lighttpd
  become: yes
  apt:
    name: lighttpd
    state: latest
    update_cache: yes

- name: change lighttpd port to 8080
  become: yes
  lineinfile:
    path: /etc/lighttpd/lighttpd.conf
    state: present
    regexp: "^server\\.port\\s*=\\s*"
    line: "server.port = 8080"
  notify:
    - restart lighttpd

- name: enable directory listing in lighttpd
  become: yes
  lineinfile:
    path: /etc/lighttpd/lighttpd.conf
    state: present
    regexp: "^server\\.dir-listing\\s*=\\s*"
    line: 'server.dir-listing = "enable"'
  notify:
    - restart lighttpd

- name: "change owner of directory {{ http_directory }}"
  become: yes
  file:
    path: "{{ http_directory }}"
    state: directory
    owner: "1000"
    group: "1000"
    mode: 0775

# flush handlers to start triggered handlers before next task is executed
- meta: flush_handlers
