# this playbook is executed on the controlserver
# ansible-playbook add-node-to-cluster.yml --extra-vars "hostname=clustarr-6cdef8c1eafc9d0996e3d59920783df7 group=masters"
---
# setup node after installation and reboot
- hosts: "{{ hostname }}"
  remote_user: ansible
  tasks:
    - include_role:
        name: docker

- hosts: proxmox
  remote_user: "{{ user }}"
  tasks:
    - include_role:
        name: proxmox
        tasks_from: group-vm
      vars:
        vm_groups:
          - "{{ group }}"

- import_playbook: group-reachable.yml

# add node to kubernetes cluster
- hosts: controlserver
  tasks:
    - include_role:
        name: rke
        tasks_from: config

    - name: setup cluster
      command: "rke up --config ~/cluster.yml"

    # display cluster pods on all nodes
    - shell: "kubectl get pod -o wide --all-namespaces --kubeconfig ~/kube_config_cluster.yml"
      register: result
    - debug:
        var: result.stdout_lines
