# this playbook is executed on the controlserver
# ansible-playbook add-node-to-cluster.yml --extra-vars "hostname=clustarr-6cdef8c1eafc9d0996e3d59920783df7 group=masters"
---
# setup node after installation and reboot
- hosts: "{{ hostname }}"
  remote_user: ansible
  tasks:
    - include_role:
        name: docker

- hosts: proxmox
  remote_user: "{{ user }}"
  tasks:
    - include_role:
        name: proxmox
        tasks_from: group-vm
      vars:
        vm_groups:
          - "{{ group }}"

- import_playbook: sync-cluster.yml
