# this playbook is executed on the controlserver
# ansible-playbook add-node.yml --extra-vars "hostname=clustarr-$(uuidgen | md5sum | awk '{print $1}')"
---
# create new node
- hosts: proxmox
  remote_user: "{{ user }}"
  tasks:
    - include_role:
        name: proxmox
        tasks_from: create-vm

    - set_fact:
        mac: "{{ vm.mac.net0 | replace(':', '-') | lower }}"

# prepare pxe for node
- hosts: localhost
  connection: local
  tasks:
    - include_role:
        name: pxe
        tasks_from: add-config
      vars:
        mac: "{{ hostvars[groups['proxmox'][0]].mac }}"

# start node
- hosts: proxmox
  remote_user: "{{ user }}"
  tasks:
    - include_role:
        name: proxmox
        tasks_from: start-vm

# refresh proxmox inventory to get new node
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - meta: refresh_inventory

# setup node after installation and reboot
- hosts: "{{ hostname }}"
  remote_user: "{{ user }}"
  gather_facts: false
  tasks:
    - name: wait for host to become reachable
      wait_for_connection:
        timeout: 1800  # 30 minutes
        sleep: 2
