# this playbook is executed on the controlserver
# ansible-playbook add-node.yml --extra-vars "hostname=clustarr-$(uuidgen | md5sum | awk '{print $1}')"
---
# create new node
- hosts: proxmox
  remote_user: "{{ user }}"
  tasks:
    - include_role:
        name: proxmox
        tasks_from: create-vm

    - set_fact:
        mac: "{{ vm.mac.net0 | replace(':', '-') | lower }}"

# prepare pxe for node
- hosts: controlserver
  tasks:
    - set_fact:
        mac: "{{ hostvars[groups['proxmox'][0]].mac }}"

    - include_role:
        name: pxe
        tasks_from: add-config

# start node
- hosts: proxmox
  remote_user: "{{ user }}"
  tasks:
    - include_role:
        name: proxmox
        tasks_from: start-vm

# setup node after installation and reboot
- hosts: "{{ hostname }}"
  remote_user: "{{ user }}"
  gather_facts: false
  tasks:
    - name: wait for host to become reachable
      wait_for_connection:
        timeout: 1800  # 30 minutes
        sleep: 2

# remove pxe config for node
- hosts: controlserver
  tasks:
    - include_role:
        name: pxe
        tasks_from: remove-config

- hosts: proxmox
  remote_user: "{{ user }}"
  tasks:
    - include_role:
        name: proxmox
        tasks_from: group-vm
      vars:
        vm_groups:
          - "independents"
