# this playbook is executed on the controlserver
# ansible-playbook remove-node.yml --extra-vars "hostname=clustarr-6cdef8c1eafc9d0996e3d59920783df7"
---
- name: gather facts from host
  hosts: "{{ hostname }}"
  remote_user: "{{ user }}"

# remove node
- hosts: proxmox
  remote_user: "{{ user }}"
  tasks:
    - include_role:
        name: proxmox
        tasks_from: remove-vm

# remove pxe config for node
- hosts: controlserver
  tasks:
    - set_fact:
        mac: "{{ hostvars[hostname].ansible_default_ipv4.macaddress | replace(':', '-') | lower }}"

    - include_role:
        name: pxe
        tasks_from: remove-config

- import_playbook: group-reachable.yml

# remove node from kubernetes cluster
- hosts: controlserver
  tasks:
    - include_role:
        name: rke
        tasks_from: config

    - name: setup cluster
      command: "rke up --config ~/cluster.yml"

    # display cluster pods on all nodes
    - shell: "kubectl get pod -o wide --all-namespaces --kubeconfig ~/kube_config_cluster.yml"
      register: result
    - debug:
        var: result.stdout_lines
