# this playbook is executed on the controlserver
# ansible-playbook remove-node.yml --extra-vars "hostname=clustarr-6cdef8c1eafc9d0996e3d59920783df7 rkeUp=false"
---
# remove group from host
- hosts: proxmox
  remote_user: "{{ user }}"
  tasks:
    - include_role:
        name: proxmox
        tasks_from: group-vm
      when:
        - hostname in groups['masters'] | default([]) or hostname in groups['workers'] | default([])
        - rkeUp | bool | default(true)

# remove node from kubernetes cluster
- import_playbook: rke-up.yml
  when:
    - hostname in groups['masters'] | default([]) or hostname in groups['workers'] | default([])
    - rkeUp | bool | default(true)

# remove node
- hosts: proxmox
  remote_user: "{{ user }}"
  tasks:
    - include_role:
        name: proxmox
        tasks_from: remove-vm
