# this playbook is executed on the controlserver
# ansible-playbook remove-node.yml --extra-vars "hostname=clustarr-worker-6cdef8c1eafc9d0996e3d59920783df7"
---
- name: gather facts from host
  hosts: "{{ hostname }}"
  remote_user: ansible

# remove node
- hosts: proxmox
  remote_user: ansible
  tasks:
    - include_role:
        name: clustarr
        tasks_from: proxmox-remove-vm

# remove pxe config for node
- hosts: localhost
  connection: local
  tasks:
    - set_fact:
        mac: "{{ hostvars[hostname].ansible_default_ipv4.macaddress | replace(':', '-') | lower }}"

    - include_role:
        name: clustarr
        tasks_from: pxe-remove-config

- import_playbook: group-workers.yml

# remove node from kubernetes cluster
- hosts: localhost
  connection: local
  tasks:
    - include_role:
        name: clustarr
        tasks_from: rke-config

    - name: setup cluster
      command: "rke up --config ~/cluster.yml"

    # display cluster pods on all nodes
    - shell: "kubectl get pod -o wide --all-namespaces --kubeconfig ~/kube_config_cluster.yml"
      register: result
    - debug:
        var: result.stdout_lines
