# this playbook is executed on the controlserver
# ansible-playbook rke-remove.yml
---
- hosts: controlserver
  tasks:
    - include_role:
        name: rke
        tasks_from: config

    - name: remove cluster
      command: "rke remove --config ~/cluster.yml --force"
