# this playbook is executed on the controlserver
# ansible-playbook rke-remove.yml
---
- hosts: controlserver
  tasks:
    - name: remove cluster
      command: "rke remove --config ~/cluster.yml --force"
