# this playbook is executed on a random host
# ansible-playbook setup-controlserver.yml
---
- hosts: controlserver
  tasks:
    - include_role:
        name: ssh
        tasks_from: generate-keypair

    - include_role:
        name: ssh

    - include_role:
        name: dnsmasq

    - include_role:
        name: lighttpd

    - include_role:
        name: pxe
        tasks_from: install

    - include_role:
        name: docker

    - include_role:
        name: rke
        tasks_from: install

    - include_role:
        name: kubectl

    - include_role:
        name: docker-compose

    - include_role:
        name: ansible

    - include_role:
        name: backend

    - include_role:
        name: frontend
