# ansible-playbook setup-controlserver.yml -u ansible -k -K
---
- hosts: controlserver
  become: yes
  roles:
    - sudo
    - ssh
    - dnsmasq
    - lighttpd
    - pxe
    - docker
    - frontend
    - ansible
