# this playbook is executed on a random host
# ansible-playbook setup-controlserver.yml
---
- hosts: controlserver
  tasks:
    - name: create ssh directory
      file:
        path: "{{ ansible_env.HOME }}/.ssh"
        state: directory
        mode: 0775

    - name: generate openssh keypair
      openssh_keypair:
        path: "{{ ansible_env.HOME }}/.ssh/id_rsa"

    - name: read openssh pubic key on remote host
      slurp:
        src: "{{ ansible_env.HOME }}/.ssh/id_rsa.pub"
      register: ssh_public_key_file

    - include_role:
        name: ssh
      vars:
        ssh_public_key: "{{ ssh_public_key_file['content'] | b64decode }}"

    - include_role:
        name: ssh

    - include_role:
        name: dnsmasq

    - include_role:
        name: lighttpd

    - include_role:
        name: pxe
        tasks_from: install

    - include_role:
        name: docker

    - include_role:
        name: frontend

    - include_role:
        name: ansible

    - include_role:
        name: rke
        tasks_from: install

    - include_role:
        name: kubectl

    - include_role:
        name: docker-compose

    - name: clone clustarr ansible repo
      git:
        repo: https://github.com/clustarr/ansible.git
        dest: "{{ ansible_env.HOME }}/ansible"
