# this playbook is executed on the controlserver
# ansible-playbook setup-nodes.yml
---
# add node ssh host keys to local known hosts
- hosts: localhost
  connection: local
  tasks:
    - include: tasks/add-host-key.yml host={{ item }}
      with_items: "{{ groups['running'] | default([]) }}"

- hosts: running
  remote_user: ansible
  tasks:
    - include_role:
        name: docker
