# this playbook is executed on a random host
# ansible-playbook setup-controlserver.yml -k -K
---
- hosts: localhost
  connection: local
  tasks:
    - include: tasks/add-host-key.yml host={{ item }}
      with_items: "{{ groups['controlserver'] }}"

- hosts: controlserver
  remote_user: ansible
  become: yes
  roles:
    - sudo
    - ssh
    - dnsmasq
    - lighttpd
    - pxe
    - docker
    - frontend
    - ansible
    - rke
    - kubectl
  tasks:
    - name: download clustarr ansible repo
      git:
        repo: https://github.com/clustarr/ansible.git
        dest: /home/ansible/ansible
