# this playbook is executed on the controlserver
# ansible-playbook setup-cluster.yml
---
- hosts: localhost
  connection: local
  roles:
    - rke-config
  tasks:
    - name: setup cluster
      command: "rke up"
