# this playbook is executed on the controlserver
# ansible-playbook setup-proxmox.yml -k
---
- hosts: localhost
  connection: local
  tasks:
    # generate openssh keypair for role ssh
    - include: tasks/create-openssh-keypair.yml

- hosts: proxmox
  remote_user: root
  tasks:
    - include_role:
        name: proxmox

    - include_role:
        name: sudo

    - include_role:
        name: ssh
