# this playbook is executed on a random host
# ansible-playbook setup-controlserver.yml -k -K
---
- hosts: controlserver
  remote_user: ansible
  tasks:
    - include_role:
        name: ssh

    - include_role:
        name: dnsmasq

    - include_role:
        name: lighttpd

    - include_role:
        name: pxe
        tasks_from: install

    - include_role:
        name: docker

    - include_role:
        name: frontend

    - include_role:
        name: ansible

    - include_role:
        name: rke
        tasks_from: install

    - include_role:
        name: kubectl

    - name: download clustarr ansible repo
      git:
        repo: https://github.com/clustarr/ansible.git
        dest: /home/ansible/ansible
