# this playbook is executed on a random host
# ansible-playbook setup-controlserver.yml -k -K
---
# add controlserver ssh host key to local known hosts
- hosts: localhost
  connection: local
  tasks:
    - include: tasks/add-host-key.yml host={{ item }}
      with_items: "{{ groups['controlserver'] }}"

- hosts: controlserver
  remote_user: ansible
  tasks:
    - include_role:
        name: ssh

    - include_role:
        name: dnsmasq

    - include_role:
        name: lighttpd

    - include_role:
        name: pxe

    - include_role:
        name: docker

    - include_role:
        name: frontend

    - include_role:
        name: ansible

    - include_role:
        name: rke

    - include_role:
        name: kubectl

    - name: download clustarr ansible repo
      git:
        repo: https://github.com/clustarr/ansible.git
        dest: /home/ansible/ansible
