# this playbook is executed on the controlserver
# ansible-playbook setup-proxmox.yml -k
---
- hosts: proxmox
  remote_user: root
  tasks:
    - include_role:
        name: clustarr
        tasks_from: proxmox-config

    - include_role:
        name: clustarr
        tasks_from: sudo

    - include_role:
        name: clustarr
        tasks_from: ssh
