# this playbook is executed on the controlserver
# ansible-playbook setup-proxmox.yml -k
---
- hosts: proxmox
  remote_user: root
  tasks:
    - include_role:
        name: proxmox

    - include_role:
        name: sudo

    - include_role:
        name: ssh
