# this playbook is executed on a random host
# ansible-playbook setup-proxmox.yml -k
---
# add node ssh host keys to local known hosts
- hosts: localhost
  connection: local
  tasks:
    - include: tasks/add-host-key.yml host={{ item }}
      with_items: "{{ groups['proxmox'] }}"

- hosts: proxmox
  remote_user: root
  roles:
    - proxmox
    - sudo
    - ssh
