# ansible-playbook setup-controlserver.yml -k -K
---
- hosts: controlserver
  remote_user: ansible
  become: yes
  roles:
    - sudo
    - ssh
    - dnsmasq
    - lighttpd
    - pxe
    - docker
    - frontend
    - ansible
    - rke
    - kubectl
