# this playbook is executed on the controlserver
# ansible-playbook setup-proxmox.yml -k
---
# add node ssh host keys to local known hosts
- hosts: localhost
  connection: local
  tasks:
    - include: tasks/add-host-key.yml
      vars:
        host: "{{ item }}"
      with_items: "{{ groups['proxmox'] }}"

    # generate openssh keypair for role ssh
    - include: tasks/create-openssh-keypair.yml

- hosts: proxmox
  remote_user: root
  tasks:
    - include_role:
        name: proxmox

    - include_role:
        name: sudo

    - include_role:
        name: ssh
