# this playbook is executed on the controlserver
# ansible-playbook setup-cluster.yml
---
- hosts: localhost
  connection: local
  tasks:
    - include_role:
        name: rke-config

    - name: setup cluster
      command: "rke up --config ~/cluster.yml"
      when: groups['running'] is defined

    # display cluster pods on all nodes
    - shell: "kubectl get pod -o wide --all-namespaces --kubeconfig ~/kube_config_cluster.yml"
      register: result
      when: groups['running'] is defined
    - debug:
        var: result.stdout_lines
      when: groups['running'] is defined
