# this playbook is executed on the controlserver
# ansible-playbook setup-proxmox.yml
---
# determine proxmox ssh user
- hosts: proxmox
  remote_user: root
  gather_facts: false
  tasks:
    - shell: exit 0
      register: result
      ignore_unreachable: yes
    - set_fact:
        ssh_user: "{{ user if result.unreachable | default(false) else ansible_ssh_user }}"
    - debug:
        var: ssh_user
    - meta: clear_host_errors

# setup proxmox with that user
- hosts: proxmox
  remote_user: "{{ ssh_user }}"
  become: "{{ True if ssh_user != 'root' else False }}"
  tasks:
    - include_role:
        name: proxmox
        tasks_from: install

    - include_role:
        name: sudo

    - include_role:
        name: ssh
