# this playbook is executed on the controlserver
# ansible-playbook sync-cluster.yml
---
- import_playbook: group-reachable.yml

- hosts: controlserver
  tasks:
    - include_role:
        name: rke
        tasks_from: config

    - name: setup cluster
      command: "rke up --config ~/cluster.yml"

    # display cluster pods on all nodes
    - shell: "kubectl get pod -o wide --all-namespaces --kubeconfig ~/kube_config_cluster.yml"
      register: result
    - debug:
        var: result.stdout_lines
