---
- name: install syslinux, pxelinux and p7zip-full
  become: yes
  apt:
    name:
      - syslinux
      - pxelinux
      - p7zip-full  # for module iso_extract
    state: latest
    update_cache: yes

- name: create tftp base directory
  file:
    path: "{{ tftp_directory }}/base"
    state: directory
    mode: 0775

- name: copy files to tftp directory
  become: yes
  copy:
    src: "{{ item }}"
    dest: "{{ tftp_directory }}/base"
    remote_src: yes
  with_items:
    - /usr/lib/PXELINUX/pxelinux.0
    - /usr/lib/syslinux/modules/bios/ldlinux.c32

- name: download ubuntu server iso
  get_url:
    url: "{{ ubuntu_server_url }}"
    checksum: "{{ ubuntu_server_checksum }}"
    dest: "{{ http_directory }}/ubuntu-server.iso"

- name: extract kernel and initramfs from ubuntu server iso
  iso_extract:
    image: "{{ http_directory }}/ubuntu-server.iso"
    dest: "{{ tftp_directory }}/base"
    files:
      - casper/vmlinuz
      - casper/initrd
