---
- name: download pxelinux.0
  get_url:
    url: "http://archive.ubuntu.com/ubuntu/dists/focal/main/installer-amd64/current/legacy-images/netboot/ubuntu-installer/amd64/pxelinux.0"
    dest: "{{ tftp_directory }}"

- name: download ubuntu server iso
  get_url:
    url: "http://releases.ubuntu.com/20.04/ubuntu-20.04-live-server-amd64.iso"
    dest: /var/www/html/ubuntu-server.iso

- name: extract kernel and initramfs from ubuntu server iso
  iso_extract:
    image: /var/www/html/ubuntu-server.iso
    dest: "{{ tftp_directory }}"
    files:
    - casper/vmlinuz
    - casper/initrd

- name: install syslinux-common
  apt:
    name: syslinux-common
    state: latest
    update_cache: yes

- name: copy file ldlinux.c32 to tftp directory
  copy:
    src: "/usr/lib/syslinux/modules/bios/ldlinux.c32"
    dest: "{{ tftp_directory }}"
    remote_src: yes

- name: create pxelinux.cfg directory
  file:
    path: "{{ tftp_directory }}/pxelinux.cfg"
    state: directory
    mode: 0775

- name: import pxelinux default config
  template:
    src: "pxelinux.cfg/default.j2"
    dest: "{{ tftp_directory }}/pxelinux.cfg/default"
    mode: 0775
    force: yes

- name: create cloud-init directory
  file:
    path: "/var/www/html/cloud-init"
    state: directory
    mode: 0775

- name: import cloud-init user-data.yml config
  template:
    src: "cloud-init/user-data.yml.j2"
    dest: "/var/www/html/cloud-init/user-data"
    mode: 0775
    force: yes

- name: touch cloud-init meta-data file
  file:
    path: /var/www/html/cloud-init/meta-data
    state: touch
    mode: 0775
