---
# add host key from new host to known hosts
# if the host key has changed, the new host key is not inserted and the tasks that follow will fail as expected

- name: "check for existing entry for host {{ host }} in known hosts"
  shell: "ssh-keygen -F {{ host }}"
  failed_when: false
  changed_when: false
  ignore_errors: yes
  register: known_host_check

- name: "write host key for host {{ host }} to known hosts"
  when: known_host_check.rc != 0
  shell: "ssh-keyscan -H {{ host }} >> ~/.ssh/known_hosts"
