---
- name: create ssh directory
  file:
    path: "/home/ansible/.ssh"
    state: directory
    mode: 0775

- name: generate openssh keypair
  openssh_keypair:
    path: /home/ansible/.ssh/id_rsa

- name: read public key
  slurp:
    src: /home/ansible/.ssh/id_rsa.pub
  register: ssh_public_key_file

- set_fact:
    ssh_public_key: "{{ ssh_public_key_file['content'] | b64decode | trim() }}"
