---
- name: add group note to proxmox vm
  proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_pass }}"
    api_host: "{{ ansible_default_ipv4.address }}"
    name: "{{ hostname }}"
    node: "{{ proxmox_api_node }}"
    sockets: "{{ proxmox_vm_sockets }}"
    cores: "{{ proxmox_vm_cores }}"
    memory: "{{ proxmox_vm_memory }}"
    description: "{\"groups\": {{ vm_groups | default([]) | to_json }}}"
    update: yes

- meta: refresh_inventory
