---
- name: remove proxmox enterprise repository
  apt_repository:
    repo: "{{ proxmox_enterprise_repository }}"
    state: absent

- name: add proxmox no-subscription repository
  apt_repository:
    repo: "{{ proxmox_no_subscription_repository }}"
    state: present
    mode: '0666'

- name: install pip
  apt:
    name:
      - python3-pip
    state: latest
    update_cache: yes

- name: install pip modules proxmoxer and requests
  pip:
    name:
      - proxmoxer
      - requests
