---
- name: remove proxmox enterprise repository
  apt_repository:
    repo: "{{ enterprise_repository }}"
    state: absent

- name: add proxmox no-subscription repository
  apt_repository:
    repo: "{{ no_subscription_repository }}"
    state: present

- name: install pip
  apt:
    name:
      - python3-pip
    state: latest
    update_cache: yes

- name: install pip modules proxmoxer and requests
  pip:
    name:
      - proxmoxer
      - requests

- name: create new proxmox vm
  proxmox_kvm:
    api_user: "{{ user }}"
    api_password: "{{ pass }}"
    api_host: "{{ host }}"
    name: "{{ name }}"
    node: pve
    sockets: 2
    cores: 4
    memory: 3072
    net: '{"net0":"virtio,bridge=vmbr0"}'
    virtio: '{"virtio0":"{{ storage }}:10"}'

- name: start proxmox vm
  proxmox_kvm:
    api_user: "{{ user }}"
    api_password: "{{ pass }}"
    api_host: "{{ host }}"
    name: "{{ name }}"
    node: pve
    state: started
