---
- name: wait for vm to appear
  retries: 15
  delay: 2
  register: vm
  until: '"status" in vm'
  proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_pass }}"
    api_host: "{{ ansible_default_ipv4.address }}"
    name: "{{ hostname }}"
    node: "{{ proxmox_api_node }}"
    state: current

# Sometimes the vm cannot be started because it does not exists even though it has been waiting for it to appear.
- pause:
    seconds: 5

- name: start proxmox vm
  proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_pass }}"
    api_host: "{{ ansible_default_ipv4.address }}"
    name: "{{ hostname }}"
    node: "{{ proxmox_api_node }}"
    state: started

- meta: refresh_inventory
