---
- name: wait for vm to appear
  retries: 15
  delay: 2
  register: vm
  until: '"status" in vm'
  proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_pass }}"
    api_host: "{{ ansible_default_ipv4.address }}"
    name: "{{ hostname }}"
    node: "{{ proxmox_api_node }}"
    state: current

- name: start proxmox vm
  proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_pass }}"
    api_host: "{{ ansible_default_ipv4.address }}"
    name: "{{ hostname }}"
    node: "{{ proxmox_api_node }}"
    state: started
