---
- name: create clustarr directory
  file:
    path: "{{ ansible_env.HOME }}/clustarr"
    state: directory
    mode: 0775

- name: clone clustarr frontend repo
  git:
    repo: https://github.com/clustarr/frontend.git
    dest: "{{ ansible_env.HOME }}/clustarr/frontend"
    force: yes

- name: import .env.local to frontend directory
  become: yes
  template:
    src: ".env.local.j2"
    dest: "{{ ansible_env.HOME }}/clustarr/frontend/.env.local"
    mode: 0775
    force: yes

- name: start frontend
  docker_compose:
    project_src: "{{ ansible_env.HOME }}/clustarr/frontend"
    build: yes
