---
- name: install dnsmasq
  become: yes
  apt:
    name: dnsmasq
    state: latest
    update_cache: yes

- name: import dnsmasq config
  become: yes
  template:
    src: "dnsmasq.conf.j2"
    dest: "/etc/dnsmasq.conf"
    mode: 0644
    force: yes
  notify:
    - restart dnsmasq

- name: create tftp directory
  become: yes
  file:
    path: "{{ tftp_directory }}"
    state: directory
    owner: "1000"
    group: "1000"
    mode: 0775

# flush handlers to start triggered handlers before next task is executed
- meta: flush_handlers
