---
- name: stop proxmox vm
  proxmox_kvm:
    api_user: "{{ proxmox_username }}"
    api_password: "{{ proxmox_password }}"
    api_host: "{{ ansible_default_ipv4.address }}"
    name: "{{ hostname }}"
    node: "{{ proxmox_node }}"
    state: stopped
    force: yes

- name: remove proxmox vm
  proxmox_kvm:
    api_user: "{{ proxmox_username }}"
    api_password: "{{ proxmox_password }}"
    api_host: "{{ ansible_default_ipv4.address }}"
    name: "{{ hostname }}"
    node: "{{ proxmox_node }}"
    state: absent
