---
- name: set authorized key for remote user
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ ssh_public_key }}"

- name: disable password authentication for root
  become: yes
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: "^#?PermitRootLogin"
    line: "PermitRootLogin prohibit-password"
  notify:
    - restart sshd

# flush handlers to start triggered handlers before next task is executed
- meta: flush_handlers
