---
- name: install ansible and sshpass
  become: yes
  apt:
    name:
      - ansible
      - sshpass
    state: latest
    update_cache: yes

- name: download ansible proxmox inventory
  become: yes
  get_url:
    url: "{{ ansible_proxmox_inventory_url }}"
    dest: /etc/ansible/proxmox.py
    mode: "+x"

# proxmox.py is currently using the shebang "#!/usr/bin/env python", python implies and python2 which is EOL
- name: adjust shebang in ansible proxmox inventory script
  become: yes
  lineinfile:
    path: /etc/ansible/proxmox.py
    state: present
    regexp: "^#!/usr/bin/env python$"
    line: "#!/usr/bin/env python3"

# TODO: make this dynamic
- name: import ansible proxmox inventory config
  become: yes
  template:
    src: "proxmox.json.j2"
    dest: "/etc/ansible/proxmox.json"
    mode: 0775
    force: yes
